from tools.tool_schema import create_schema
from tools.system_tools.system_tools import get_directory_name, scan_directory, identify_file_types, organize_files_by_type, extract_info_from_todo
from tools.internet_tools.internet_tools import compress_image, compress_pdf, send_email, add_calendar_event, share_stock_market_data, send_daily_stock_update